HT_21/app/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include("ui.urls")),
    path('', include("scrapper.urls")),
    path('basket/', include("basket.urls")),
    path('admin/', admin.site.urls),
]

HT_21/basket/urls.py
from django.urls import path

from . import views

app_name = 'basket'

urlpatterns = [
    path('', views.view_basket, name="view_basket"),
    path('add-to-basket/', views.add_to_basket, name="add"),
    path(
        'change-basket-quantity/',
        views.change_basket_quatity,
        name="change_quantity"),
    path(
        'delete-basket-product/',
        views.delete_basket_product,
        name="delete_product"),
    path('clear-basket/', views.clear_basket, name="clear_basket"),
]

HT_21/scrapper/urls.py
from django.urls import path

from . import views

app_name = 'scrapper'

urlpatterns = [
    path('scrape/', views.scrape_outer_data, name="scrape_outer_data"),
    path('products/', views.list_products, name="list_products"),
    path('products/<int:pk>/', views.product_detail, name="product_detail"),
    path('products/edit/<int:pk>/', views.product_detail_edit, name="product_detail_edit"),
    path('category/<int:pk>/', views.category_list, name="category_list"),
]

HT_21/ui/urls.py
from django.urls import path

from ui.views import index


app_name = 'ui'

urlpatterns = [
    path("", index, name="index"),
]

HT_21/scrapper/models.py
from django.db import models


# Create your models here.
class Category(models.Model):
    """
    Категорії продуктів - пов'язана модель
    """
    title = models.CharField(max_length=30)

    def __str__(self):
        return self.title


class Product(models.Model):
    """
    Дані по продукту отриманому із rozetka_ip
    """
    item_id = models.CharField(max_length=30)
    title = models.CharField(max_length=130)
    sell_status = models.CharField(max_length=12, default='available')
    old_price = models.FloatField()
    current_price = models.FloatField()
    href = models.TextField()
    brand = models.CharField(max_length=50, null=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    url_image_preview = models.TextField(null=True)
    url_image_big = models.TextField(null=True)

    def __str__(self):
        # print(f"---{dir(self)=}")
        return (f"{self.title} : {self.current_price:.2f} : "
                f"{self.category} : "
                f"{self.str_available}")

    @property
    def is_available(self):
        return self.sell_status == 'available'

    @property
    def str_available(self):
        if self.is_available:
            return 'В наявності'
        else:
            return 'Відсутній'


# на видалення
class BackgroundProcessMessage(models.Model):
    """
    Тимчасове повідомлення від фонового
    процесу про його виконання
    """
    value = models.TextField()

HT_21/scrapper/forms.py
from django import forms
from django.core.validators import MinValueValidator, MaxValueValidator

from .models import Product


class AddProductToBasketForm(forms.Form):
    product_pk = forms.IntegerField(widget=forms.HiddenInput())
    quantity = forms.IntegerField(
        label="Потрібна кількість:",
        validators=[
            MinValueValidator(1, message="Значення не може бути менше 1"),
            MaxValueValidator(20, message="Значення не може бути більше 20")
        ])


class ProductIdForm(forms.Form):
    product_pk = forms.IntegerField(widget=forms.HiddenInput())


class ProductEditForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = '__all__'
        # fields = [
        #     'item_id',
        #     'title',
        #     'sell_status',
        #     'old_price',
        #     'current_price',
        #     'href',
        #     'brand',
        #     'category',
        #     'url_image_preview',
        #     'url_image_big',
        # ]
        # widgets = {
        #     'name': Textarea(attrs={'cols': 80, 'rows': 20}),
        # }
        # labels = {
        #     'name': _('Writer'),
        # }
        # help_texts = {
        #     'name': _('Some useful help text.'),
        # }
        # error_messages = {
        #     'name': {
        #         'max_length': _("This writer's name is too long."),
        #     },
        # }
        # field_classes = {
        #     'slug': MySlugFormField,
        # }

HT_21/scrapper/views.py
import re
import threading
import uuid
from pathlib import Path

from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.forms.models import model_to_dict
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required, user_passes_test

from .forms import AddProductToBasketForm, ProductEditForm
from .models import Product
from .models import Category
from .models import BackgroundProcessMessage
from .api_rozetka import get_data_from_scraper_and_put_into_db


# Create your views here.
@user_passes_test(lambda user: user.is_superuser, login_url='/')
def scrape_outer_data(request):
    context = {
        "title": "Scraper page :: HT_20",
        # "helper_messages": [],
    }

    if request.method == "POST":
        str_need_ids = request.POST["list_ids"]
        lst_ids = re.split(r"[\s,;]+", str_need_ids.strip())
        # get information about list_ids from scrapper
        if lst_ids and lst_ids[0] != '':
            # Present ids to load - run thread
            name_thread = f"Scrapper_Thread-{str(uuid.uuid4())[:6]}"
            thread = threading.Thread(
                target=get_data_from_scraper_and_put_into_db,
                name=name_thread,
                args=(lst_ids, name_thread),
                daemon=None)
            thread.start()
    else:
        # Get method - first enter
        messages.info(
            request,
            (Path(Path.cwd()) / "scrapper" / "templates" / "scrapper" /
                "start_ids_rozetka.txt").read_text(encoding="utf-8")
        )

    # Вибір останніх 10 продуктів із БД
    last_ten_products = Product.objects.all().order_by('-id')[:10]
    products = reversed(last_ten_products)
    context["products"] = products

    proceses = []
    for thread in threading.enumerate():
        if thread.name.startswith("Scrapper_Thread-"):
            proceses.append(thread)
    context["proceses"] = proceses

    # Prepare helper message
    bg_messages_model = BackgroundProcessMessage.objects.all()
    if bg_messages_model:
        for bg_message_model in bg_messages_model:
            messages.info(
                request,
                f"{bg_message_model.value}"
            )
            bg_message_model.delete()

    return render(request, 'scrapper/scrape_data.html', context)


def list_products(request):
    user = User.objects.first()
    context = {
        "title": "List of scrapered products :: HT_20",
        "products": Product.objects.all(),
        "categories": Category.objects.all(),
        }
    return render(request, 'scrapper/list_products.html', context)


def category_list(request, pk):
    # Вивід продуктів у вказаній категорії
    target_category = Category.objects.get(pk=pk)
    print(f"category_list:{target_category=}")
    context = {
        "title": f"Наявні товари категорії '{target_category.title}' :: HT_21",
        "products": Product.objects.filter(category=target_category),
        }
    print(f"category_list:{context=}")
    return render(request, 'scrapper/list_category_products.html', context)


def product_detail(request, pk):
    basket = request.session.setdefault('basket', {})
    # print(f"product_detail:{basket=} {pk=}")
    product_basket_quantity = basket.get(str(pk))
    # print(f"product_detail:{product_basket_quantity=}")
    storage_messages = messages.get_messages(request)
    product_basket_err_message = ""
    for message in storage_messages:
        if message.level_tag == 'error' and "basket" in message.extra_tags:
            product_basket_err_message = message.message

    context = {
        "title": "List of scrapered products :: HT_20",
        "err_message": request.session.get("err_message"),
        "product": get_object_or_404(Product, pk=pk),
        "product_basket": {
            "quantity": product_basket_quantity,
            "message_err": product_basket_err_message
            },
        'form_add': AddProductToBasketForm(
            initial={'product_pk': pk, "quantity": 1}
            )
    }
    # Якщо відбувся redirect на цю сторінку і з сесії присутні дані форми,
    # що не відповідають обмеженням валідації - (можливо колхоз №2)
    if "form_add_values" in request.session:
        form_add = AddProductToBasketForm(request.session["form_add_values"])
        form_add.is_valid()
        del request.session["form_add_values"]
        request.session.save()
        context["form_add"] = form_add
    # print(f"product_detail:{context=}")
    return render(
        request, 'scrapper/products_detail.html', context)


def product_detail_edit(request, pk):
    print(f"product_detail_edit:{request.method=}, {pk=}")

    context = {
       "title": "Редагування продукта :: HT_21",
       "pk": pk,
    }
    if request.method == "GET":
        context["form"] = ProductEditForm(instance=Product.objects.get(pk=pk)) 
    else:
        # POST need save modified data Product
        form = ProductEditForm(request.POST, instance=Product.objects.get(pk=pk))
        print(f"product_detail_edit:{request.POST=}")
        if form.is_valid():
            print(f"product_detail_edit:valid:{form.cleaned_data=}")
            form.save(commit=True)
            return redirect(reverse("scrapper:product_detail", kwargs={'pk': context["pk"]}))
        else:
            context["form"] = form 
    return render(
        request, 'scrapper/products_detail_edit.html', context)

HT_21/scrapper/templates/scrapper/list_category_products.html
{% extends 'ui/base.html' %}
{% load static %}

{% block ext_style %}
<style type="text/css">
    .available {
        background-color: lightgreen;
    }
    .unavailable {
        background-color: lightcoral;
    }
</style>
{% endblock %}

{% block content %}
        <div class="">
            <h3>{{ title }}</h3>
            <hr>
                {% for product in products %}
                    <p class="product-item">{{ product.title }} : {{ product.current_price|floatformat:2 }}&nbsp;грн.
                       <span class="{% if product.is_available %}available{% else %}unavailable{% endif %}">{{ product.str_available }}</span> 
                       <a href="{% url 'scrapper:product_detail' pk=product.pk %}">детально...</a>
                    </p> 
                {% endfor %}
        </div>
{% endblock %}

HT_21/scrapper/templates/scrapper/list_products.html
{% extends 'ui/base.html' %}
{% load static %}

{% block ext_style %}
<style type="text/css">
    .available {
        border-bottom: 1px dotted #DDEEDD;
    }
    .unavailable {
        padding: 0 3px;
        border: 2px dashed red;
    }
</style>
{% endblock %}

{% block content %}
        <div class="">
            <h3>Наявні продукти - із Rozetka:<img src="{% static 'rozetka.svg' %}" width="30" height="30"></h3>
            <hr>
            {% for product in products %}
                <p class="product-item">{{ product.title }} : {{ product.current_price|floatformat:2 }}&nbsp;грн.
                   <span class="{% if product.is_available %}available{% else %}unavailable{% endif %}">{{ product.str_available }}</span> 
                   <a href="{% url 'scrapper:product_detail' pk=product.pk %}">детально...</a>
                </p> 
            {% endfor %}
        </div>
{% endblock %}

HT_21/scrapper/templates/scrapper/products_detail.html
{% extends 'ui/base.html' %}
{% load static %}

{% block ext_style %}
<style type="text/css">
    .available {
        background-color: lightgreen;
    }
    .unavailable {
        background-color: lightcoral;
    }
    .error_add {
        font-style: italic;
        font-size: -2pt;
        color: red;
        border: 1px dotted #ED365D;
        padding: 2px;
    }
    .error_basket {
        font-style: italic;
        color: red;
        border-bottom: 1px dotted #ED365D;
    }
</style>
{% endblock %}

{% block content %}
   
        <div class="">
            <h3>Детальні дані про зібраний продукт отриманого із магазину Rozetka:<img src="{% static 'rozetka.svg' %}" width="30" height="30"></h3>
            <hr>
            <p class="product-item-detail">Код продукта: <span class="item-value">{{ product.item_id }}</span></p> 
            <p class="product-item-detail">Заголовок: <span class="item-value">{{ product.title }}</span> </p> 
            <p class="product-item-detail">Категорія: <span class="item-value">{{ product.category }}</span>, Бренд: <span class="item-value">{% if product.brand %}{{ product.brand }} {% else %} {{ '-відсутній-' }} {% endif %}</span></p> 
            <p class="product-item-detail">Ціна: <span class="item-value">{{ product.current_price }}</span>, стара ціна: <span class="item-value">{% if product.old_price != 0 %} {{ product.old_price }} {% else %} {{ '-не встановлено-' }} {% endif %}</span></p> 
            <p>Доступність: <span class="{% if product.is_available %}available{% else %}unavailable{% endif %}">{{ product.is_available|yesno:'Є в наявності,Немає в наявності' }}</span></p>
            <p><a href="{{ product.href }}">Посилання на оригінал</a></p>
            <img src="{{ product.url_image_preview }}" alt="Зображення продукта">
        </div>
        <hr>
        {% if product.is_available %}
            {% if request.user.is_authenticated %}
            {% if product_basket.quantity %}
                <p>В корзині: {{ product_basket.quantity }} шт. <span class="error_basket">{{ product_basket.message_err }}</span></p>
            {% endif %}
        <form action="{% url 'basket:add' %}" method="POST">
            <div>Занести цей продукт в корзину:</div>
            {% csrf_token %}
            {% for field in form_add %}
                {% if field.is_hidden %}
                    {{ field }}
                {% else %}
                  <div>
                    {{ field.label_tag }}  {{ field }}
                    {% if field.errors %}
                        {% for error_mess in field.errors %}
                            <span class="error_add">
                                {{ error_mess|safe }}
                            </span>
                        {% endfor %}
                    {% endif %}
                    {% if field.help_text %}
                        <span>{{ field.help_text|safe }}</span>
                    {% endif %}
                  </div>
                {% endif %}
            {% endfor %}
            <button type="submit">Add to basket</button>
        </form>
        {% endif %}
        {% endif %}
        {% if request.user.is_superuser %}
        <div style="margin-top:10px;border: 1px solid gray;">
        <p style="padding: 0;margin:0;">Панель керування адміністратора:</p>
        <a href="{% url 'scrapper:product_detail_edit' pk=product.pk %}">
            <button type="button">Edit product</button>        
        </a>
        <form action="#" method="POST">
            {% csrf_token %}
            <button type="submit">Delete product</button>            
        </form>
        </div>
        {% endif %}
{% endblock %}

HT_21/scrapper/templates/scrapper/products_detail_edit.html
{% extends 'ui/base.html' %}
{% load static %}

{% block ext_style %}
<style>
</style>
{% endblock %}

{% block content %}
    <h3>Редагування даних про зібраний продукт</h3>
    <hr>
    <form action="{% url 'scrapper:product_detail_edit' pk=pk %}" method="POST">
        {% csrf_token %}
        {% for field in form %}
            <div>{{ field.label_tag }} {% if field.label_tag != 'Item id' %}{{ field }}{% endif %}</div>
        {% endfor %}
        
        <button type="submit">Save</button>
    </form>

{% endblock %}

HT_21/scrapper/templates/scrapper/scrape_data.html
{% extends 'ui/base.html' %}
{% block ext_style %}
<style type="text/css">
    .available {
        color: green;
    }
    .unavailable {
        color: red;
    }
</style>
{% endblock %}
{% block content %}
    <section class="row">
        <div class="col field_input">
            <p class="title_message">Щоб поновити сторінку натиснути кнопку "Виконати завантаження" з пустим списком</p>
            <form action="" method="POST"> {% csrf_token %}
               <textarea class="textarea_ids" rows="10" cols="5" name="list_ids" placeholder="Внести сюди перелік id товарів які необхідно завантажити. роздільники (, \t \n \r)"></textarea> 
               <button type="submit">Виконати завантаження</button>
               <div class="title_message">
                {% if messages %}
                    {% for message in messages %} 
                        <div>{{ message }}</div>
                    {% endfor %}
                {% endif %}
               </div>
            </form>
        </div>
        <div class="col preview_data">
            {% if proceses %}
            <p>Фонові процеси завантаження даних:</p>
                <ul>
                {% for process in proceses %}
                <li>name: {{ process.name }}</li>
                {% endfor %}
                </ul>
            <hr>  
            {% endif %}

            {% if products %}
            <p>Останні 10 завантажених продуктів:</p>
            {% for product in products %}
                <p>
                    <a href="{% url 'scrapper:product_detail' pk=product.pk %}">{{ product.title }}</a>
                    : <span class="{%if product.is_available%}available{%else%}unavailable{%endif%}">{{ product.str_available }}</span> 

                </p>
            {% endfor %}
            {% endif %}
        </div>
    </section>
{% endblock %}