HT_21/app/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include("ui.urls")),
    path('', include("scrapper.urls")),
    path('basket/', include("basket.urls")),
    path('admin/', admin.site.urls),
]

HT_21/scrapper/urls.py
from django.urls import path

from . import views

app_name = 'scrapper'

urlpatterns = [
    path('scrape/', views.scrape_outer_data, name="scrape_outer_data"),
    path('products/', views.list_products, name="list_products"),
    path('products/<int:pk>/', views.product_detail, name="product_detail"),
    path('products/edit/<int:pk>/', views.product_detail_edit, name="product_detail_edit"),
    path('category/<int:pk>/', views.category_list, name="category_list"),
]

HT_21/ui/urls.py
from django.urls import path

from ui.views import index


app_name = 'ui'

urlpatterns = [
    path("", index, name="index"),
]

HT_21/ui/models.py
from django.db import models

# Create your models here.

HT_21/ui/views.py
from django.shortcuts import render


# Create your views here.
def index(request):
    return render(
        request,
        'ui/index.html',
        {"title": "Index page :: HT_20", }
    )

HT_21/ui/templates/ui/base.html
<!DOCTYPE html>
<html>
<head>{% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="{% static 'scrapper.css' %}">
    <style>
        .message-row{
            display: flex;
        }
        .message-box{
            background-color: #F4A1ED;
            margin: 2px;
            padding: 0 4px 4px 4px;
            border-radius: 10px;
            border: 2px outset red;
        }
        .message-gap{
            flex-grow: 1;
        }
        .message_close_button{
            border:1px solid red;
            font-size: 16pt;
            padding:0 2px;
            color:red; 
            border-radius: 5px;
        }

    </style>
    {% block ext_style %}
    {% endblock %}
</head>
<body>
    <nav class="navigation">
        <span class=""><a href="/">Головна</a></span>
        {% if request.user.is_superuser %}<span class=""><a href="/scrape">Додати продукти</a></span>{% endif %}
        <span class=""><a href="/products">Мої продукти</a></span>
        <span class="space">&nbsp;</span>
        <span class="basket"><a href="/basket">Корзина</a></span>
        <span class="user">
            {% if request.user.is_authenticated %}
            Hello, {{request.user.username}}
            <a href="{% url 'admin:logout' %}?next={{request.path}}">LOGOUT</a>
            {% else %}
            <a href="{% url 'admin:login' %}?next={{request.path}}">LOGIN</a>
            {% endif %}
        </span>
    </nav>
    <main>
        {% for message in messages %}
            {% if not message.extra_tags %}
            <div class="message-row">
        <div class="message-box">{{ message }} <span title="Click to hide" href="#" onclick="this.parentElement.style.display='none';" class="message_close_button">&#10006;</span></div>
        <div class="message-gap">&nbsp;</div>
        </div>
            {% endif %}
        {% endfor %}
        
        {% block content %}
        {% endblock %}
    </main>
    <footer>
        <p>ДЗ #19, #20 - Навчальний проект магазина (Джанго) [Скраппер, Показ продуктів, Робота з корзиною]<span class="rozetka_api"> за участі: <img src="{% static 'rozetka.svg' %}" width="20" height="20"> Rozetka_api ДЗ #15</span></p>
    </footer>
</body>
</html>

HT_21/ui/templates/ui/index.html
{% extends 'ui/base.html' %}

{% block content %}
<h2>Опис проекта</h2>
<hr>

<h3>Домашнє завдання #21 - Підтримка авторизації, Категорії продукта(нова модель, зв'язок, відображення)</h3>
<h4>Базуючись на ДЗ 20 та 19, реалізувати наступний функціонал:</h4>
<ol>
    <li>&#10004;Створити форму для авторизації користувача. Нові користувачі додаються із Адмінки.</li>
    <li>Якщо користувач неправильний - редіректнуть на сторінку логіна і вивести відповідне повідомлення (messages)</li>
    <li>&#10004;Якщо користувач незалогінений - сайт показується, але є кнопка (або посилання) "LOG IN"</li>
    <li>&#10004;Якщо користувач залогінений - на місці тієї кнопки (посилання) показується його ім'я і поруч кнопка (посилання) "LOG OUT"</li>
    <li>&#10004;Додайте підтримку категорій продуктів.</li>
    <li>&#10004;На головній сторінці виводяться всі продукти. При цьому вгорі є перелік доступних категорій - при натисканні на конкретну категорію показується сторінка із продуктами тільки цієї категорії.</li>
    <li>&#10004;Якщо користувач є суперюзером - на сторінці товара показується кнопка для його редагування або видалення.</li>
    <li>&#10004;Якщо користувач залогінений - він може додати продукт в корзину.</li>
    <li>Якщо користувач не залогінений - він може тільки продивлятись продукти.</li>
    <li>При спробі незалогіненого або звичайного юзера відкрити сторінку редагування продукта - він редіректиться на головну сторінку і виводиться відповідне повідомлення.</li>
    <li>До сторінки додавання нових продуктів доступ має тільки суперюзер</li>
</ol>

<hr>
<h3>Домашнє завдання #20 - Реалізація корзини. Зміна кількості подуктів, видалення одного продукта, очищення корзини</h3>
<ol>
    <li> &#10004; Додати сторінку корзини;</li>
    <li> &#10004; Реалізувати додавання продукта до корзини;</li>
    <li> &#10004; Реалізувати зміну кількості продукта [В корзині] (перевіряти на від'ємне значення як введеного значення, так і отриманої кількості);</li>
    <li> &#10004; Видалення одного продукта [З корзини]; </li>
    <li> &#10004; Очищення всієї корзини;</li>
    <li>Додатково - сформувати pdf-форму заказа</li>
</ol>

<hr>
<h3>Домашнє завдання #19 - Створення Django проекта, скрепер, показ зібраної інформації:</h3>
<ol>
    <li> &#10004; Сторінка (<a href ="{% url 'scrapper:scrape_outer_data' %}">"Додати продукти"</a>), на якій Розміщено textfield, в який можна ввести будь-яку кількість ID продуктів.</li>
    <li> &#10004; При відправленні форми, запускається скрейпер, що збирає всі продукти із визначеними ID із сайту Розетки.</li>
    <li>Процес скрейпінга відбувається "на бекграунді" - основний потік виконання не блокується:
        <ul>
            <li> &#10004; В фоновий потік передається розібраний список отриманий із textfield, без застосування передічі через модель.</li> 
            <li> &#10004; Інформація про фоновий процес виводиться справа на панелі сторінки "Додати продукти"</li>
            <li> &#10004; Результат виконання фонового процесу заноситься у модель (BackgroundProcessMessage) повідомлень про результат виконання. (Кількість запитів(Успішних, Збійних), Результати вставки у таблицю)</li>
            <li> &#10004; Після виконання фонового процесу, результат виводиться під полем вводу потрібних ID із сайту Розетки, рядки що вивелись із Таблиці видвляються</li>
            <li> &#10004; Наступне поновлення сторінки витирає ці повідомлення</li>
        </ul> 
    </li>
    <li> &#10004; Сторінка (<a href ="{% url 'scrapper:list_products' %}">"Мої продукти"</a>), на якій вивести всі продукти, які є в системі, із зазначенням їхніх основних параметрів (назва, ціна)</li>
    <li> &#10004; Сторінка "Продукт", (до якої переходити із сторінки "Мої продукти") на ній виводяться вся зібрана інформація про обраний продукт: 
        <ul>
            <li>ІД,</li>
            <li>назва,</li>
            <li>короткий опис (якщо є),</li>
            <li>категорія,</li>
            <li>бренд,</li>
            <li>ціна,</li>
            <li>стара ціна (якщо є),</li>
            <li>лінка на продукт (на сайті Розетки)</li>
            <li>зображення продукта (лінк на зображення на сайті Розетки)[може завантажитись не зразу]</li>
        </ul>
    </li>
</ol>

{% endblock %}